Update and rename ci.yml to ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -25,7 +25,9 @@ jobs:
       - name: Run Tests
         id: run_tests
         run: |
-          pytest || echo "TEST_FAILED=true" >> $GITHUB_ENV
+          export PYTHONPATH=$PYTHONPATH:$(pwd) 
+          pytest tests/main_test.py || echo "TEST_FAILED=true" >> $GITHUB_ENV
+
 
       - name: Comment on PR if Tests Fail
         if: env.TEST_FAILED == 'true'
