Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -8,6 +8,10 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    permissions:
+      issues: write      # Make sure to grant comment permissions
+      pull_requests: write  # Permissions for pull request management
+
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -26,8 +30,7 @@ jobs:
         id: run_tests
         run: |
           export PYTHONPATH=$PYTHONPATH:$(pwd) 
-          pytest tests/main_test.py || echo "TEST_FAILED=true" >> $GITHUB_ENV
-
+          pytest tests/ || echo "TEST_FAILED=true" >> $GITHUB_ENV
 
       - name: Comment on PR if Tests Fail
         if: env.TEST_FAILED == 'true'
